--- #YAML:1.0
name:               Hash-Flatten
version:            1.19
abstract:           flatten/unflatten complex data hashes
author:
    - British Broadcasting Corporation
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Trace:        0
    Test::Assertions:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
